apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rk-sync.fullname" . }}-pvc
  labels:
    {{- include "rk-sync.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
